<h2 align = 'center' style='color:green'>Hear_Disease W/ Ensemble Learning <h2>

In [2]:
import pandas as pd
import numpy as np

In [3]:
heart_disease = pd.read_csv('heart.csv')
heart_disease.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
heart_disease.shape

(918, 12)

In [5]:
heart_disease.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [6]:
outlier_col = ['RestingBP','Cholesterol','MaxHR','Oldpeak']

In [7]:
for rem_outlier in outlier_col:
    heart_disease[rem_outlier+' zscore']= (heart_disease[rem_outlier]-heart_disease[rem_outlier].mean())/heart_disease[rem_outlier].std()

heart_disease.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,RestingBP zscore,Cholesterol zscore,MaxHR zscore,Oldpeak zscore
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.824621,1.382175,-0.831979
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.171867,0.753746,0.105606
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.769768,-1.524307,-0.831979
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.138964,-1.131539,0.574398
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.034736,-0.581664,-0.831979

In [8]:
heart_disease_no_outlier = heart_disease

In [9]:
for rem_outlier in outlier_col:
    heart_disease_no_outlier = heart_disease_no_outlier[(heart_disease_no_outlier[rem_outlier+' zscore']>-3)&(heart_disease_no_outlier[rem_outlier+' zscore']<3)] 

heart_disease_no_outlier.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,RestingBP zscore,Cholesterol zscore,MaxHR zscore,Oldpeak zscore
count,899.000000,899.000000,899.000000,899.000000,899.000000,899.000000,899.000000,899.000000,899.000000,899.000000,899.000000
mean,53.497219,132.027809,198.005562,0.232481,136.917686,0.861513,0.547275,-0.019915,-0.007259,0.004254,-0.024238
std,9.456073,17.120895,107.157779,0.422649,25.356740,1.007626,0.498037,0.924746,0.979646,0.995931,0.944735
min,28.000000,80.000000,0.000000,0.000000,63.000000,-2.000000,0.000000,-2.830079,-1.817444,-2.898994,-2.707149
25%,47.000000,120.000000,174.500000,0.000000,120.000000,0.000000,0.000000,-0.669570,-0.222149,-0.660218,-0.831979
50%,54.000000,130.000000,222.000000,0.000000,138.000000,0.500000,1.000000,-0.129442,0.212101,0.046764,-0.363186
75%,60.000000,140.000000,266.000000,0.000000,156.000000,1.500000,1.000000,0.410685,0.614353,0.753746,0.574398
max,77.000000,185.000000,518.000000,1.000000,202.000000,4.000000,1.000000,2.841258,2.918160,2.560478,2.918360

In [10]:
heart_disease_no_outlier.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,RestingBP zscore,Cholesterol zscore,MaxHR zscore,Oldpeak zscore
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.824621,1.382175,-0.831979
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.171867,0.753746,0.105606
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.769768,-1.524307,-0.831979
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.138964,-1.131539,0.574398
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.034736,-0.581664,-0.831979

In [11]:
heart_disease_no_outlier['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [12]:
dfd = pd.get_dummies(heart_disease_no_outlier,
                     columns=['Sex','ChestPainType','RestingECG','ExerciseAngina','ST_Slope'],
                     drop_first=True,
                     dtype=float
                     )
dfd.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,RestingBP zscore,Cholesterol zscore,MaxHR zscore,Oldpeak zscore,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,0.410685,0.824621,1.382175,-0.831979,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,49,160,180,0,156,1.0,1,1.490940,-0.171867,0.753746,0.105606,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,37,130,283,0,98,0.0,0,-0.129442,0.769768,-1.524307,-0.831979,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,48,138,214,0,108,1.5,1,0.302660,0.138964,-1.131539,0.574398,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
4,54,150,195,0,122,0.0,0,0.950812,-0.034736,-0.581664,-0.831979,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

In [13]:
X = dfd.drop(['HeartDisease','RestingBP zscore','Cholesterol zscore','MaxHR zscore','Oldpeak zscore'],axis='columns')
X

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,49,160,180,0,156,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,37,130,283,0,98,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,48,138,214,0,108,1.5,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
4,54,150,195,0,122,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
914,68,144,193,1,141,3.4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
915,57,130,131,0,115,1.2,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
916,57,130,236,0,174,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
917,38,138,175,0,173,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

In [21]:
Y = dfd['HeartDisease']
Y.value_counts()

HeartDisease
1    492
0    407
Name: count, dtype: int64

In [16]:
from sklearn.preprocessing import StandardScaler
x_scaled = StandardScaler().fit_transform(X)
x_scaled

array([[-1.42815446,  0.46590022,  0.84963584, ..., -0.8229452 ,
        -0.99888827,  1.13469459],
       [-0.47585532,  1.63471366, -0.16812204, ..., -0.8229452 ,
         1.00111297, -0.88129441],
       [-1.7455875 , -0.1185065 ,  0.79361247, ..., -0.8229452 ,
        -0.99888827,  1.13469459],
       ...,
       [ 0.3706328 , -0.1185065 , -0.62564622, ...,  1.21514774,
         1.00111297, -0.88129441],
       [ 0.3706328 , -0.1185065 ,  0.35476274, ..., -0.8229452 ,
         1.00111297, -0.88129441],
       [-1.63977649,  0.34901888, -0.21480818, ..., -0.8229452 ,
        -0.99888827,  1.13469459]], shape=(899, 15))

In [22]:
from sklearn import svm
from sklearn.model_selection import cross_val_score

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x_scaled,Y,test_size=0.2)

In [19]:
X_train.shape

(719, 15)

In [23]:
model = svm.SVC(gamma='auto',C=1,kernel='rbf')
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

0.8833333333333333

In [29]:
c_score = cross_val_score(model,x_scaled,Y,cv=5)
c_score.mean()

np.float64(0.8319615145872129)

In [30]:
from sklearn.ensemble import BaggingClassifier

In [ ]:
clf = BaggingClassifier(
   estimator=model,
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=10
)
clf.fit(x_scaled,Y)
clf.oob_score_

0.8743047830923248

In [ ]:
c_score_2 = cross_val_score(clf,x_scaled,Y,cv=5)
c_score_2.mean()

np.float64(0.8252948479205463)

In [39]:
from sklearn.tree import DecisionTreeClassifier
c_score_3 = cross_val_score(DecisionTreeClassifier(),x_scaled,Y,cv=5)
c_score_3.mean()

np.float64(0.7362942271880819)

In [40]:
clf_2 = BaggingClassifier(
    estimator= DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=10
)

In [41]:
c_score_4 = cross_val_score(clf_2,x_scaled,Y,cv=5)
c_score_4.mean()

np.float64(0.8041340782122905)